usemySQL: false
mySQLconn: jdbc:mysql://localhost:3306/minecraft
mySQLuname: root
mySQLpass: password
globalUseEconomy: false
allowWorldTeleport: true
defaultWEAnywhere: false
NbClearSpools: 3
NbBlocksPerClearStep: 50000
AdvancedLogging: false
LoadAllPlotsOnStart: false
#Internal Database Upgrade Settings
#Don't modify unless you know what you are doing. The plugin will do this for you.
CoreDatabaseUpdate: true
mySQLConverter: true
